// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

use glib::GStr;

#[doc(alias = "SPICE_WEBDAV_CLIPBOARD_FOLDER_PATH")]
pub static WEBDAV_CLIPBOARD_FOLDER_PATH: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::SPICE_WEBDAV_CLIPBOARD_FOLDER_PATH) };
