// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

use glib::{bitflags::bitflags, prelude::*, translate::*};
use std::fmt;

bitflags! {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    #[doc(alias = "SpiceInputsLock")]
    pub struct InputsLock: u32 {
        #[doc(alias = "SPICE_INPUTS_SCROLL_LOCK")]
        const SCROLL_LOCK = ffi::SPICE_INPUTS_SCROLL_LOCK as _;
        #[doc(alias = "SPICE_INPUTS_NUM_LOCK")]
        const NUM_LOCK = ffi::SPICE_INPUTS_NUM_LOCK as _;
        #[doc(alias = "SPICE_INPUTS_CAPS_LOCK")]
        const CAPS_LOCK = ffi::SPICE_INPUTS_CAPS_LOCK as _;
    }
}

impl fmt::Display for InputsLock {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        <Self as fmt::Debug>::fmt(self, f)
    }
}

#[doc(hidden)]
impl IntoGlib for InputsLock {
    type GlibType = ffi::SpiceInputsLock;

    #[inline]
    fn into_glib(self) -> ffi::SpiceInputsLock {
        self.bits()
    }
}

#[doc(hidden)]
impl FromGlib<ffi::SpiceInputsLock> for InputsLock {
    #[inline]
    unsafe fn from_glib(value: ffi::SpiceInputsLock) -> Self {
        skip_assert_initialized!();
        Self::from_bits_truncate(value)
    }
}

impl StaticType for InputsLock {
    #[inline]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::spice_inputs_lock_get_type()) }
    }
}

impl glib::HasParamSpec for InputsLock {
    type ParamSpec = glib::ParamSpecFlags;
    type SetValue = Self;
    type BuilderFn = fn(&str) -> glib::ParamSpecFlagsBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        |name| Self::ParamSpec::builder(name)
    }
}

impl glib::value::ValueType for InputsLock {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for InputsLock {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        from_glib(glib::gobject_ffi::g_value_get_flags(value.to_glib_none().0))
    }
}

impl ToValue for InputsLock {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_flags(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<InputsLock> for glib::Value {
    #[inline]
    fn from(v: InputsLock) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}

bitflags! {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    #[doc(alias = "SpiceSessionVerify")]
    pub struct SessionVerify: u32 {
        #[doc(alias = "SPICE_SESSION_VERIFY_PUBKEY")]
        const PUBKEY = ffi::SPICE_SESSION_VERIFY_PUBKEY as _;
        #[doc(alias = "SPICE_SESSION_VERIFY_HOSTNAME")]
        const HOSTNAME = ffi::SPICE_SESSION_VERIFY_HOSTNAME as _;
        #[doc(alias = "SPICE_SESSION_VERIFY_SUBJECT")]
        const SUBJECT = ffi::SPICE_SESSION_VERIFY_SUBJECT as _;
    }
}

impl fmt::Display for SessionVerify {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        <Self as fmt::Debug>::fmt(self, f)
    }
}

#[doc(hidden)]
impl IntoGlib for SessionVerify {
    type GlibType = ffi::SpiceSessionVerify;

    #[inline]
    fn into_glib(self) -> ffi::SpiceSessionVerify {
        self.bits()
    }
}

#[doc(hidden)]
impl FromGlib<ffi::SpiceSessionVerify> for SessionVerify {
    #[inline]
    unsafe fn from_glib(value: ffi::SpiceSessionVerify) -> Self {
        skip_assert_initialized!();
        Self::from_bits_truncate(value)
    }
}

impl StaticType for SessionVerify {
    #[inline]
    fn static_type() -> glib::Type {
        unsafe { from_glib(ffi::spice_session_verify_get_type()) }
    }
}

impl glib::HasParamSpec for SessionVerify {
    type ParamSpec = glib::ParamSpecFlags;
    type SetValue = Self;
    type BuilderFn = fn(&str) -> glib::ParamSpecFlagsBuilder<Self>;

    fn param_spec_builder() -> Self::BuilderFn {
        |name| Self::ParamSpec::builder(name)
    }
}

impl glib::value::ValueType for SessionVerify {
    type Type = Self;
}

unsafe impl<'a> glib::value::FromValue<'a> for SessionVerify {
    type Checker = glib::value::GenericValueTypeChecker<Self>;

    #[inline]
    unsafe fn from_value(value: &'a glib::Value) -> Self {
        skip_assert_initialized!();
        from_glib(glib::gobject_ffi::g_value_get_flags(value.to_glib_none().0))
    }
}

impl ToValue for SessionVerify {
    #[inline]
    fn to_value(&self) -> glib::Value {
        let mut value = glib::Value::for_value_type::<Self>();
        unsafe {
            glib::gobject_ffi::g_value_set_flags(value.to_glib_none_mut().0, self.into_glib());
        }
        value
    }

    #[inline]
    fn value_type(&self) -> glib::Type {
        Self::static_type()
    }
}

impl From<SessionVerify> for glib::Value {
    #[inline]
    fn from(v: SessionVerify) -> Self {
        skip_assert_initialized!();
        ToValue::to_value(&v)
    }
}
