// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct GlScanout(Boxed<ffi::SpiceGlScanout>);

    match fn {
        copy => |ptr| glib::gobject_ffi::g_boxed_copy(ffi::spice_gl_scanout_get_type(), ptr as *mut _) as *mut ffi::SpiceGlScanout,
        free => |ptr| glib::gobject_ffi::g_boxed_free(ffi::spice_gl_scanout_get_type(), ptr as *mut _),
        type_ => || ffi::spice_gl_scanout_get_type(),
    }
}
