// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct QmpStatus(Shared<ffi::SpiceQmpStatus>);

    match fn {
        ref => |ptr| ffi::spice_qmp_status_ref(ptr),
        unref => |ptr| ffi::spice_qmp_status_unref(ptr),
        type_ => || ffi::spice_qmp_status_get_type(),
    }
}
