// This file was generated by gir (https://github.com/gtk-rs/gir)
// from 
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((gint) SPICE_CHANNEL_CLOSED);
    PRINT_CONSTANT((gint) SPICE_CHANNEL_ERROR_AUTH);
    PRINT_CONSTANT((gint) SPICE_CHANNEL_ERROR_CONNECT);
    PRINT_CONSTANT((gint) SPICE_CHANNEL_ERROR_IO);
    PRINT_CONSTANT((gint) SPICE_CHANNEL_ERROR_LINK);
    PRINT_CONSTANT((gint) SPICE_CHANNEL_ERROR_TLS);
    PRINT_CONSTANT((gint) SPICE_CHANNEL_NONE);
    PRINT_CONSTANT((gint) SPICE_CHANNEL_OPENED);
    PRINT_CONSTANT((gint) SPICE_CHANNEL_SWITCHING);
    PRINT_CONSTANT((gint) SPICE_CLIENT_ERROR_AUTH_NEEDS_PASSWORD);
    PRINT_CONSTANT((gint) SPICE_CLIENT_ERROR_AUTH_NEEDS_PASSWORD_AND_USERNAME);
    PRINT_CONSTANT((gint) SPICE_CLIENT_ERROR_AUTH_NEEDS_USERNAME);
    PRINT_CONSTANT((gint) SPICE_CLIENT_ERROR_FAILED);
    PRINT_CONSTANT((gint) SPICE_CLIENT_ERROR_USB_DEVICE_LOST);
    PRINT_CONSTANT((gint) SPICE_CLIENT_ERROR_USB_DEVICE_REJECTED);
    PRINT_CONSTANT((gint) SPICE_CLIENT_ERROR_USB_SERVICE);
    PRINT_CONSTANT(SPICE_GTK_MAJOR_VERSION);
    PRINT_CONSTANT(SPICE_GTK_MICRO_VERSION);
    PRINT_CONSTANT(SPICE_GTK_MINOR_VERSION);
    PRINT_CONSTANT((guint) SPICE_INPUTS_CAPS_LOCK);
    PRINT_CONSTANT((guint) SPICE_INPUTS_NUM_LOCK);
    PRINT_CONSTANT((guint) SPICE_INPUTS_SCROLL_LOCK);
    PRINT_CONSTANT((gint) SPICE_QMP_PORT_VM_ACTION_CONTINUE);
    PRINT_CONSTANT((gint) SPICE_QMP_PORT_VM_ACTION_LAST);
    PRINT_CONSTANT((gint) SPICE_QMP_PORT_VM_ACTION_PAUSE);
    PRINT_CONSTANT((gint) SPICE_QMP_PORT_VM_ACTION_POWER_DOWN);
    PRINT_CONSTANT((gint) SPICE_QMP_PORT_VM_ACTION_QUIT);
    PRINT_CONSTANT((gint) SPICE_QMP_PORT_VM_ACTION_RESET);
    PRINT_CONSTANT((gint) SPICE_SESSION_MIGRATION_CONNECTING);
    PRINT_CONSTANT((gint) SPICE_SESSION_MIGRATION_MIGRATING);
    PRINT_CONSTANT((gint) SPICE_SESSION_MIGRATION_NONE);
    PRINT_CONSTANT((gint) SPICE_SESSION_MIGRATION_SWITCHING);
    PRINT_CONSTANT((guint) SPICE_SESSION_VERIFY_HOSTNAME);
    PRINT_CONSTANT((guint) SPICE_SESSION_VERIFY_PUBKEY);
    PRINT_CONSTANT((guint) SPICE_SESSION_VERIFY_SUBJECT);
    PRINT_CONSTANT(SPICE_WEBDAV_CLIPBOARD_FOLDER_PATH);
    return 0;
}
