// This file was generated by gir (https://github.com/gtk-rs/gir)
// from 
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "SpiceAudio", sizeof(SpiceAudio), alignof(SpiceAudio));
    printf("%s;%zu;%zu\n", "SpiceAudioClass", sizeof(SpiceAudioClass), alignof(SpiceAudioClass));
    printf("%s;%zu;%zu\n", "SpiceChannel", sizeof(SpiceChannel), alignof(SpiceChannel));
    printf("%s;%zu;%zu\n", "SpiceChannelClass", sizeof(SpiceChannelClass), alignof(SpiceChannelClass));
    printf("%s;%zu;%zu\n", "SpiceChannelEvent", sizeof(SpiceChannelEvent), alignof(SpiceChannelEvent));
    printf("%s;%zu;%zu\n", "SpiceClientError", sizeof(SpiceClientError), alignof(SpiceClientError));
    printf("%s;%zu;%zu\n", "SpiceCursorChannel", sizeof(SpiceCursorChannel), alignof(SpiceCursorChannel));
    printf("%s;%zu;%zu\n", "SpiceCursorChannelClass", sizeof(SpiceCursorChannelClass), alignof(SpiceCursorChannelClass));
    printf("%s;%zu;%zu\n", "SpiceCursorShape", sizeof(SpiceCursorShape), alignof(SpiceCursorShape));
    printf("%s;%zu;%zu\n", "SpiceDisplayChannel", sizeof(SpiceDisplayChannel), alignof(SpiceDisplayChannel));
    printf("%s;%zu;%zu\n", "SpiceDisplayChannelClass", sizeof(SpiceDisplayChannelClass), alignof(SpiceDisplayChannelClass));
    printf("%s;%zu;%zu\n", "SpiceDisplayMonitorConfig", sizeof(SpiceDisplayMonitorConfig), alignof(SpiceDisplayMonitorConfig));
    printf("%s;%zu;%zu\n", "SpiceDisplayPrimary", sizeof(SpiceDisplayPrimary), alignof(SpiceDisplayPrimary));
    printf("%s;%zu;%zu\n", "SpiceGlScanout", sizeof(SpiceGlScanout), alignof(SpiceGlScanout));
    printf("%s;%zu;%zu\n", "SpiceInputsChannel", sizeof(SpiceInputsChannel), alignof(SpiceInputsChannel));
    printf("%s;%zu;%zu\n", "SpiceInputsChannelClass", sizeof(SpiceInputsChannelClass), alignof(SpiceInputsChannelClass));
    printf("%s;%zu;%zu\n", "SpiceInputsLock", sizeof(SpiceInputsLock), alignof(SpiceInputsLock));
    printf("%s;%zu;%zu\n", "SpiceMainChannel", sizeof(SpiceMainChannel), alignof(SpiceMainChannel));
    printf("%s;%zu;%zu\n", "SpiceMainChannelClass", sizeof(SpiceMainChannelClass), alignof(SpiceMainChannelClass));
    printf("%s;%zu;%zu\n", "SpicePlaybackChannel", sizeof(SpicePlaybackChannel), alignof(SpicePlaybackChannel));
    printf("%s;%zu;%zu\n", "SpicePlaybackChannelClass", sizeof(SpicePlaybackChannelClass), alignof(SpicePlaybackChannelClass));
    printf("%s;%zu;%zu\n", "SpicePortChannel", sizeof(SpicePortChannel), alignof(SpicePortChannel));
    printf("%s;%zu;%zu\n", "SpicePortChannelClass", sizeof(SpicePortChannelClass), alignof(SpicePortChannelClass));
    printf("%s;%zu;%zu\n", "SpiceQmpPortVmAction", sizeof(SpiceQmpPortVmAction), alignof(SpiceQmpPortVmAction));
    printf("%s;%zu;%zu\n", "SpiceQmpStatus", sizeof(SpiceQmpStatus), alignof(SpiceQmpStatus));
    printf("%s;%zu;%zu\n", "SpiceRecordChannel", sizeof(SpiceRecordChannel), alignof(SpiceRecordChannel));
    printf("%s;%zu;%zu\n", "SpiceRecordChannelClass", sizeof(SpiceRecordChannelClass), alignof(SpiceRecordChannelClass));
    printf("%s;%zu;%zu\n", "SpiceSession", sizeof(SpiceSession), alignof(SpiceSession));
    printf("%s;%zu;%zu\n", "SpiceSessionClass", sizeof(SpiceSessionClass), alignof(SpiceSessionClass));
    printf("%s;%zu;%zu\n", "SpiceSessionMigration", sizeof(SpiceSessionMigration), alignof(SpiceSessionMigration));
    printf("%s;%zu;%zu\n", "SpiceSessionVerify", sizeof(SpiceSessionVerify), alignof(SpiceSessionVerify));
    printf("%s;%zu;%zu\n", "SpiceSmartcardChannel", sizeof(SpiceSmartcardChannel), alignof(SpiceSmartcardChannel));
    printf("%s;%zu;%zu\n", "SpiceSmartcardChannelClass", sizeof(SpiceSmartcardChannelClass), alignof(SpiceSmartcardChannelClass));
    printf("%s;%zu;%zu\n", "SpiceSmartcardManager", sizeof(SpiceSmartcardManager), alignof(SpiceSmartcardManager));
    printf("%s;%zu;%zu\n", "SpiceSmartcardManagerClass", sizeof(SpiceSmartcardManagerClass), alignof(SpiceSmartcardManagerClass));
    printf("%s;%zu;%zu\n", "SpiceUsbDeviceManager", sizeof(SpiceUsbDeviceManager), alignof(SpiceUsbDeviceManager));
    printf("%s;%zu;%zu\n", "SpiceUsbDeviceManagerClass", sizeof(SpiceUsbDeviceManagerClass), alignof(SpiceUsbDeviceManagerClass));
    printf("%s;%zu;%zu\n", "SpiceUsbredirChannel", sizeof(SpiceUsbredirChannel), alignof(SpiceUsbredirChannel));
    printf("%s;%zu;%zu\n", "SpiceUsbredirChannelClass", sizeof(SpiceUsbredirChannelClass), alignof(SpiceUsbredirChannelClass));
    printf("%s;%zu;%zu\n", "SpiceWebdavChannel", sizeof(SpiceWebdavChannel), alignof(SpiceWebdavChannel));
    printf("%s;%zu;%zu\n", "SpiceWebdavChannelClass", sizeof(SpiceWebdavChannelClass), alignof(SpiceWebdavChannelClass));
    return 0;
}
