[options]
work_mode = "sys"
library = "SpiceClientGLib"
version = "2.0"
min_cfg_version = "0.39"
single_version_file = "."
girs_directories = ["../../gir-files", "../../"]

external_libraries = [
    "GLib",
    "GObject",
    "Gio",
]
